---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:

    - name: Uninstall apache if needed
      ansible.builtin.apt:
        update_cache: yes
        name: apache2
        state: absent

    - name: docker.io
      ansible.builtin.apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      ansible.builtin.apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker python module
      pip:
        name: 
        state: 

    - name: revert requests to 2.31.0 to bypass https://github.com/docker/docker-py/issues/3256
      ansible.builtin.command:
        cmd: 

    - name: download and launch a docker web container
      docker_container:
        name: 
        image: 
        state: 
        published_ports: 

    - name: Enable docker service
      systemd:
        name: 
        enabled: 